name: zugclient
description: Flutter client framework for the ZugServ library
version: 0.5.7
homepage: https://github.com/JohnChernoff/zugclient

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  oauth2: ^2.0.2
  provider: ^6.1.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  package_info_plus: ^4.2.0
  universal_html: ^2.2.4
  logging: ^1.2.0
  ini: ^2.1.0
  audioplayers: ^6.1.2
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_ui_auth: ^1.16.1
  http: ^1.4.0
  zug_net:
    git: "https://github.com/JohnChernoff/ZugNetFlutter"
  zug_utils:
    #path: "C:/Users/jac107/IdeaProjects/flutter/zug_utils"
    git: "https://github.com/JohnChernoff/zug_utils"
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/